using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeApi.Migrations
{
    /// <inheritdoc />
    public partial class UpdateBankAccountSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Step 1: Add id column as nullable first
            migrationBuilder.AddColumn<long>(
                name: "id",
                schema: "dotnet",
                table: "bank_account",
                type: "bigint",
                nullable: true);

            // Step 2: Populate id with sequence values for existing records
            migrationBuilder.Sql(@"
                CREATE SEQUENCE IF NOT EXISTS dotnet.bank_account_id_seq;
                DO $$
                DECLARE
                    max_id bigint;
                BEGIN
                    SELECT MAX(id) INTO max_id FROM dotnet.bank_account WHERE id IS NOT NULL;
                    IF max_id IS NULL THEN
                        -- No existing ids, start sequence at 1 (nextval will return 1)
                        PERFORM setval('dotnet.bank_account_id_seq', 1, false);
                    ELSE
                        -- Existing ids, continue from max (nextval will return max_id + 1)
                        PERFORM setval('dotnet.bank_account_id_seq', max_id, false);
                    END IF;
                END $$;
                UPDATE dotnet.bank_account SET id = nextval('dotnet.bank_account_id_seq') WHERE id IS NULL;
                -- Drop the temporary sequence as PostgreSQL will create its own when we add identity
                DROP SEQUENCE IF EXISTS dotnet.bank_account_id_seq;
            ");

            // Step 3: Make id NOT NULL first
            migrationBuilder.AlterColumn<long>(
                name: "id",
                schema: "dotnet",
                table: "bank_account",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);

            // Step 3b: Add identity to id column and sync sequence
            migrationBuilder.Sql(@"
                ALTER TABLE dotnet.bank_account 
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                
                -- Sync the identity sequence with the current max id value
                SELECT setval(pg_get_serial_sequence('dotnet.bank_account', 'id'), COALESCE((SELECT MAX(id) FROM dotnet.bank_account), 1), true);
            ");

            // Step 4: Add new columns (swift_code, branch_code)
            migrationBuilder.AddColumn<string>(
                name: "swift_code",
                schema: "dotnet",
                table: "bank_account",
                type: "character varying(11)",
                maxLength: 11,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "branch_code",
                schema: "dotnet",
                table: "bank_account",
                type: "character varying(20)",
                maxLength: 20,
                nullable: true);

            // Step 5: Drop the unique index on account_number
            migrationBuilder.DropIndex(
                name: "IX_bank_account_account_number",
                schema: "dotnet",
                table: "bank_account");

            // Step 6: Drop the composite primary key
            migrationBuilder.DropPrimaryKey(
                name: "PK_bank_account",
                schema: "dotnet",
                table: "bank_account");

            // Step 7: Add primary key on id
            migrationBuilder.AddPrimaryKey(
                name: "PK_bank_account",
                schema: "dotnet",
                table: "bank_account",
                column: "id");

            // Step 8: Add unique index on (account_number, bank_name) to prevent duplicates
            migrationBuilder.CreateIndex(
                name: "IX_bank_account_account_number_bank_name",
                schema: "dotnet",
                table: "bank_account",
                columns: new[] { "account_number", "bank_name" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop the unique index on (account_number, bank_name)
            migrationBuilder.DropIndex(
                name: "IX_bank_account_account_number_bank_name",
                schema: "dotnet",
                table: "bank_account");

            // Drop primary key on id
            migrationBuilder.DropPrimaryKey(
                name: "PK_bank_account",
                schema: "dotnet",
                table: "bank_account");

            // Drop new columns
            migrationBuilder.DropColumn(
                name: "swift_code",
                schema: "dotnet",
                table: "bank_account");

            migrationBuilder.DropColumn(
                name: "branch_code",
                schema: "dotnet",
                table: "bank_account");

            // Drop id column
            migrationBuilder.DropColumn(
                name: "id",
                schema: "dotnet",
                table: "bank_account");

            // Restore composite primary key
            migrationBuilder.AddPrimaryKey(
                name: "PK_bank_account",
                schema: "dotnet",
                table: "bank_account",
                columns: new[] { "account_number", "bank_name" });

            // Restore unique index on account_number
            migrationBuilder.CreateIndex(
                name: "IX_bank_account_account_number",
                schema: "dotnet",
                table: "bank_account",
                column: "account_number",
                unique: true);
        }
    }
}
